### ISSUE TITLE
Add support as a GitHub Action

### ISSUE THREAD

**Issue by lannonbr** [tscholze/python-twitch-teams-to-markdown-converter#1]
Hey @tscholze. So As you know, we use your script to create a listing for the LiveCoders  team on Twitch. I was wanting to automate the process of keeping the script up to date, and with such, I converted it into a GitHub Action. I have it in a [branch](https://github.com/lannonbr/python-twitch-teams-to-markdown-converter/tree/GitHubActions) on my fork currently and I likely still will clean it up, but would it be alright to submit a PR back to your repo?

Here's a public test repo where you can see a test run: https://github.com/lannonbr/LiveCodersMarkdownTableActionTest

**Comment by tscholze** [comment]
Hi @lannonbr,
Wow great! It would be great if you open a PR. Create to see my script in action (no pun intended).

If you have any feature requests, please let me know!

**Comment by tscholze** [comment]
Thanks @lannonbr!
I added you to the list of authors.
